### ISSUE TITLE
Quiz Feedback

### ISSUE THREAD

**Issue by afiiif** [yunusbahtiar22/project-quote#3]
Maaf baru sempat review mas...

Jazaakallaah.. Mantab sekali mas..
- Functional udah oke ✅ 
- Pakai semantic HTML 👍 
- Validasi form memanfaatkan attribut HTML 👍 
- Penggunaan context jg sudah oke 👍 

Dari saya ada beberapa feedback biar semakin bagus lagi ya mas..

1.)  
File `/dist/style.min.css` jangan lupa diinclude juga di repository ini. Saya lihat di sini hanya ada file SCSS.

2.)  
Untuk manipulasi DOM, baiknya tidak menggunakan fungsi native di JavaScript.  
Contoh: `element.classList.add("sesuatu")`  
Sebaiknya manfaatkan state.

3.)  
Pengulangan code.  
Saya lihat ada code ini diulang berkali2, sebaiknya dibuat sebuah component terpisah saja:
```
<div className="progress-container">
  <Progress
    step={
      currentForm === 0
        ? 0.5
        : currentForm === 1
        ? 1.5
        : currentForm === 2
        ? 2.5
        : 3
    }
  />
</div>
<hr className="form-divider" />
```

Barokallaahu fiik. Semoga dimudahkan 🙏

**Comment by afiiif** [comment]
Oiya, satu lagi, input fieldnya belum ada placeholdernya mas..

**Comment by yunomeister22** [comment]
jazakallahu khoiron mas Afif atas reviewnya, untuk feedbacknya sudah ditindak lanjuti yaa mas disini a4d87a2eaae9fc2d8ad4254e99480f4287af3223.
baarakallahu fiik mas.

**Comment by aditiopangestu** [comment]
masya Allah, dari saya sudah oke mas, bisa lanjut ke level 3, yang menarik di sini, untuk form yang pertama menggunakan pendekatan Uncontrolled Component pada TextInput, sambil menunggu level 3 dimulai, bisa dicoba juga menggunakan Controlled Component pada TextInput, penjelasan lebih lanjut bisa dipelajari di https://react.dev/learn/sharing-state-between-components#controlled-and-uncontrolled-components

**Comment by yunomeister22** [comment]
Baik mas, nanti saya coba pakai controlled component. Sebenarnya sebelumnya pakai mas cuma dirasa kurang efektif plus state error yg lumayan rumit. Akhirnya saya pakai [Constraint Validation API](https://developer.mozilla.org/en-US/docs/Web/HTML/Constraint_validation). Jazakallahu khoiron mas @aditiopangestu atas reviewnya.

**Comment by afiiif** [comment]
Sori baru bales lagi..

Mantab mas, dari saya juga sudah oke 👍 Sudah bisa lanjut ke level 3
